### PR TITLE
Fix "uppercase character in header name: Cache-Control"

### LINKED ISSUE #431: Uppercase character in header name: Cache-Control
Using [rack](https://github.com/rack/rack) > 3.0.0 requires all response header keys to be lowercase: https://github.com/rack/rack/commit/472e12f5b6505cc2fdd3b5e529b616b3a2d5fbf8

If not it throws:
`Rack::Lint::LintError: uppercase character in header name: Cache-Control`

### PR DESCRIPTION
**Pull request by cschlack**
Using rack < 3.0.0 requires all response header keys to be lowercase: https://github.com/rack/rack/commit/472e12f5b6505cc2fdd3b5e529b616b3a2d5fbf8

fixes #431

### CODE REVIEW

**Comment by marcelolx** [comment]
Thank you!

File: lib/sidekiq-scheduler/extensions/web.rb [hunk 1]
```diff
@@ -10,5 +10,5 @@
   Sidekiq::Web.use Rack::Static, urls: ['/stylesheets-scheduler'],
                                  root: ASSETS_PATH,
                                  cascade: true,
-                                 header_rules: [[:all, { 'Cache-Control' => 'public, max-age=86400' }]]
+                                 header_rules: [[:all, { 'cache-control' => 'public, max-age=86400' }]]
```
Comment (pbstriker38) [inline lib/sidekiq-scheduler/extensions/web.rb:13]: Should this also have `, no-cache="Set-Cookie"`?

https://github.com/sidekiq/sidekiq/issues/5936

Comment (mperham) [reply lib/sidekiq-scheduler/extensions/web.rb:13]: It shouldn’t need this at all. Extensions should be able to add asset paths and reuse the default Rack::Static instance that Sidekiq installs.

Comment (marcelolx) [reply lib/sidekiq-scheduler/extensions/web.rb:13]: hmm interesting, I will check this when I have some time!
